name: smash_banners
description: A web app for making cool smash banners made in Flutter and with the help of AI

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # Theme related
  google_fonts: ^2.1.0

  # Extra widgets
  future_progress_dialog: ^0.2.0
  expandable: ^5.0.1
  flutter_spinbox: ^0.6.0
  dropdown_search: ^2.0.0
  wheel_chooser: ^1.0.0
  flutter_colorpicker: ^0.6.0

  # Navigation
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/characters/banjo_and_kazooie/
    - assets/characters/bayonetta/
    - assets/characters/bowser/
    - assets/characters/bowser_jr/
    - assets/characters/byleth/
    - assets/characters/captain_falcon/
    - assets/characters/chrom/
    - assets/characters/cloud/
    - assets/characters/corrin/
    - assets/characters/daisy/
    - assets/characters/dark_pit/
    - assets/characters/dark_samus/
    - assets/characters/diddy_kong/
    - assets/characters/donkey_kong/
    - assets/characters/duck_hunt/
    - assets/characters/dq_hero/
    - assets/characters/dr_mario/
    - assets/characters/falco/
    - assets/characters/fox/
    - assets/characters/ganondorf/
    - assets/characters/greninja/
    - assets/characters/ice_climbers/
    - assets/characters/ike/
    - assets/characters/incineroar/
    - assets/characters/inkling/
    - assets/characters/isabelle/
    - assets/characters/jigglypuff/
    - assets/characters/joker/
    - assets/characters/kazuya/
    - assets/characters/ken/
    - assets/characters/king_dedede/
    - assets/characters/king_k_rool/
    - assets/characters/kirby/
    - assets/characters/link/
    - assets/characters/little_mac/
    - assets/characters/lucario/
    - assets/characters/lucas/
    - assets/characters/lucina/
    - assets/characters/luigi/
    - assets/characters/mario/
    - assets/characters/marth/
    - assets/characters/mega_man/
    - assets/characters/meta_knight/
    - assets/characters/mewtwo/
    - assets/characters/mii_fighter/
    - assets/characters/minmin/
    - assets/characters/mr_game_and_watch/
    - assets/characters/ness/
    - assets/characters/olimar/
    - assets/characters/pac_man/
    - assets/characters/palutena/
    - assets/characters/peach/
    - assets/characters/pichu/
    - assets/characters/pikachu/
    - assets/characters/piranha_plant/
    - assets/characters/pit/
    - assets/characters/pokemon_trainer/
    - assets/characters/pyra/
    - assets/characters/richter/
    - assets/characters/ridley/
    - assets/characters/rob/
    - assets/characters/robin/
    - assets/characters/rosalina_and_luma/
    - assets/characters/roy/
    - assets/characters/ryu/
    - assets/characters/samus/
    - assets/characters/sephiroth/
    - assets/characters/sheik/
    - assets/characters/shulk/
    - assets/characters/simon/
    - assets/characters/snake/
    - assets/characters/sonic/
    - assets/characters/sora/
    - assets/characters/steve/
    - assets/characters/terry/
    - assets/characters/toon_link/
    - assets/characters/villager/
    - assets/characters/wario/
    - assets/characters/wii_fit_trainer/
    - assets/characters/wolf/
    - assets/characters/yoshi/
    - assets/characters/young_link/
    - assets/characters/zelda/
    - assets/characters/zero_suit_samus/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
